name: intro-jupyter-notebooks
channel_priority: strict
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - jupyterlab
  - nb_conda_kernels
  - jupyterlab-lsp
  - pandas
  - folium
  - rise
  - ipycytoscape
  - networkx
  - pip
  - pip:
    - git+https://github.com/krassowski/python-language-server.git@main
