name: intro-jupyter-notebooks
channels:
  - conda-forge
dependencies:

  # Entwicklungsumgebung
  - python=3.10
  - jupyterlab=3
  - jupyterlab-spellchecker
  - jupyterlab-lsp
  - python-lsp-server
  - pylint

  # benoetigte Bibliotheken
  - pandas
  - matplotlib
  - folium
  - ipycytoscape
  - ipywidgets
  - ipycanvas
  - networkx
  - scipy
